<a href="https://colab.research.google.com/github/AbbySnt/EstadisticaAplicada_1990002/blob/main/sesion2_g44_10ago.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Estadistica Aplicada

Sesion 2 - 10 agosto

Yessica Abigail Santiago Hernandez 199002

Una lista en ptthon es una coleccion de objetos que pueden ser de distinto tipo

In [2]:
#sintaxis para la creacion de una lista
alumno = ['Yessica','santiago','22']

In [3]:
type(alumno)

list

In [5]:
estadistica_g44 = ['andrea','ana','carlos','hugo']

In [6]:
estadistica_g44

['andrea', 'ana', 'carlos', 'hugo']

In [7]:
#seleccion de un elemento de una lista (ana)
#python comienza a contar desde 0 andrea-0 ana-1, carlos-2, hugo-3

estadistica_g44[1]

'ana'

In [8]:
estadistica_g44[2]

'carlos'

In [9]:

#seleccion de varios elementos
estadistica_g44[0:2] # se va a la posicion 2 pero no la incluye (no incluye a carlos)

['andrea', 'ana']

In [10]:
#añadir elementos a la lista ya creada
estadistica_g44.append('raul')

In [11]:
estadistica_g44

['andrea', 'ana', 'carlos', 'hugo', 'raul']

In [12]:
#eliminar elementos de una lista
estadistica_g44.remove('hugo')

In [13]:
estadistica_g44

['andrea', 'ana', 'carlos', 'raul']

In [14]:
yo_enFCFM = ['abigail','act','89']

In [15]:
#darle un valor a una variable en base a una lista
mi_promedio = yo_enFCFM[2]
mi_carrera = yo_enFCFM[1]

In [16]:
print('promedio:',mi_promedio,'mi carrera:',mi_carrera)

promedio: 89 mi carrera: act


# librerias/paquetes/modulos
Una libreria en python es un conjunto de codigos que le indican a python como hacer determinadas cosas



## Las librerias basicas son:

numerical python o numpy = numerical python, le ayuda a python a manejar numeros en cualquier estructura

pandas = para manejar datas

matplotlib = es una graficadora

statistical models = ayuda con modelos estadisticos


## Para usar una libreria:
1. primero se instala
2. Se le indica a python que la utilica

In [18]:
pip install yfinance

In [ ]:
#tambien se le pueden poner abreviaciones a las librerias de la siguiente forma

In [20]:
import yfinance as yf

In [ ]:
yf.download('US.MX', '')

# Numpy (numerical python)
Libreria que le sirve a python para manejra numeros

La estructura basica de numpy son los arreglos. Y a su vez un arreglo es una coleccion de objetos del mismo tipo, la mayoria de las veces en caso de numpy son arreglos de tipo numerico

Vamos a suponer que tenemos la venta de aguas de la cafeteria de FCFM de la semana: Lunes 23, Martes 35, Miercoles 40, Jueves 28 y Viernes 20

In [23]:
ventas = [23,35,40,28,20]

In [21]:
import numpy as np

In [24]:
#convertir una lista en un arreglo
ventas = np.array(ventas)

In [25]:
type(ventas)

numpy.ndarray

In [26]:
ventas

array([23, 35, 40, 28, 20])

In [27]:
# funcion de suma
np.sum(ventas)

146

In [28]:
#Funcion de multiplicacion
np.prod(ventas)

18032000

In [29]:
#Funcion para el valor maximo
np.max(ventas)

40

In [30]:
#Funcion para el valor minimo
np.min(ventas)

20

In [31]:
#Funcion para sacar la media (promedio)
np.mean(ventas)

29.2

In [32]:
#funcion para sacar la mediana
np.median(ventas)

28.0

In [33]:
#funcion para sacar la varianza
np.var(ventas)

54.96

In [34]:
#Funcion para sacar la desviacion estandar
np.std(ventas)

7.413501197140255

In [36]:
#Funcion para sacar la varianza muestral
np.var(ventas,ddof=1)

68.7

In [37]:
#Funcion para sacara la desviacion estandar muestral
np.std(ventas,ddof=1)

8.28854631404084

In [38]:
#Generacion de vectores
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
#generacin de vectores donde se especifica donde empieza
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
#generacion de vectores donde se especifica donde empieza, donde termina y como va aumentando
np.arange(1,100,15)

array([ 1, 16, 31, 46, 61, 76, 91])

In [42]:
#vector de ceros
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [43]:

#vector de unos
np.ones(5)

array([1., 1., 1., 1., 1.])

In [45]:
#vector de numeros diferentes
np.full(6,8)

array([8, 8, 8, 8, 8, 8])

In [46]:
#generacion de numeros aleatorios
np.random.randint(0,25,10)
#10 numeros aleatorios del 0 al 25

array([17, 11,  6, 10, 19, 18, 12, 18,  1, 22])

In [47]:
#generar numeros aleatorios y que cuando se vuelva a correr vuelvan a ser los mismos numeros aleatorios (FIJAR LA SEMILLA DE LA ALEATORIEDAD)-- garantiza que siempre sean los mismos numeros aleatorios
np.random.seed(12)
aleatorios = np.random.randint(0,25,10)

In [51]:
#ordenar los numeros
aleatorios = np.sort(aleatorios) # va a guardar el orden de los numeros

In [52]:
#contar los numeros aleatorios (cuantos hay)
len(aleatorios)

10

In [53]:
np.random.seed(19)
aleatorios2 = np.random.randint(0,25,9)

In [55]:
#generar ua lista de numeros
numeros=[2.45,9.89,12.4567]

In [ ]:
#se va a convertir en arreglo, obtenemos media y redondeamos a dos decimales

1. convertir en arreglo
2. Obtenemos la media
3. Redondeamos a dos decimales

*se va a hacer por medio de dos maneras por funcion y por metodo*

In [56]:
#Funcion
round (np.mean(np.array(numeros)),2)

#round (numero, decimales) -- funciona para redondear

8.27

In [58]:
#Metodo
np.array(numeros).mean().round(2)

8.27